export default function Head() {
  return (
    <>
      <title>Reserve at Milestone Restaurant | OpenTable</title>
      <meta content='width=device-width, initial-scale=1' name='viewport' />
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' type='image/png' href='/restaurant.png' />
    </>
  )
}
